### ISSUE TITLE
org.omnifaces.FACES_VIEWS_SCAN_PATHS only works when running with quarkus:dev

### ISSUE THREAD

**Issue by newk5** [adminfaces/quarkus-omnifaces#83]
Extensionless mapping only seems to work when running the application with quarkus:dev.

After packaging the app with: mvn package  and running the final jar, it doesn't work. There is no error message, just shows an empty page saying "Not found"

**Comment by melloware** [comment]
I have a feeling the bug is here:

```java
@SuppressWarnings("unchecked")
	private static Set<String[]> getRootPathsAndExtensions(ServletContext servletContext) {
		Set<String[]> rootPaths = (Set<String[]>) servletContext.getAttribute(SCAN_PATHS);

		if (rootPaths == null) {
			rootPaths = new HashSet<>();
			rootPaths.add(new String[] { WEB_INF_VIEWS, null });
			Set<String> multiViewsPaths = new TreeSet<>(Collator.getInstance(ENGLISH)); // Makes sure ! is sorted before /.

			for (String rootPath : csvToList(servletContext.getInitParameter(FACES_VIEWS_SCAN_PATHS_PARAM_NAME))) {
				boolean multiViews = rootPath.endsWith("/*");

				if (multiViews) {
					rootPath = rootPath.substring(0, rootPath.lastIndexOf("/*"));
				}

				String[] rootPathAndExtension = rootPath.contains("*") ? rootPath.split(quote("*")) : new String[] { rootPath, null };
				rootPathAndExtension[0] = normalizeRootPath(rootPathAndExtension[0]);
				rootPaths.add(rootPathAndExtension);

				if (multiViews) {
					multiViewsPaths.add(rootPathAndExtension[0]);
				}
			}

			servletContext.setAttribute(SCAN_PATHS, unmodifiableSet(rootPaths));
			servletContext.setAttribute(MULTIVIEWS_PATHS, unmodifiableSet(multiViewsPaths));
		}

		return rootPaths;
	}
```

OmniFaces must not be scanning or calculating something correctly with Quarkus since Quarkus uses different paths /resources instead of /WEB-INF ?

**Comment by newk5** [comment]
Yea it could be. Quarkus has 2 packaging modes, the new "fast-jar" mode which is the default and  ``quarkus.package.type=uber-jar`` which creates an uber jar. For now, uber-jar packaging mode is broken with myfaces (see [here](https://issues.apache.org/jira/browse/MYFACES-4427 ) ), so I'm using ["fast-jar"](https://quarkus.io/guides/maven-tooling#fast-jar) mode, for anyone else looking into this, make sure you're not using  ``quarkus.package.type=uber-jar``

**Comment by melloware** [comment]
Hey when I create a fast-jar iwth my Quarkus Faces showcase and run `java -jar target/quarkus-app/quarkus-run.jar` I am getting this error:

```
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
        ... 15 more
Caused by: javax.xml.parsers.FactoryConfigurationError: Provider org.apache.xerces.jaxp.DocumentBuilderFactoryImpl not found
        at javax.xml.parsers.DocumentBuilderFactory.newInstance(Unknown Source)
        at org.omnifaces.util.Xml.createDocumentBuilder(Xml.java:83)
```

Have you seen this error before?

**Comment by melloware** [comment]
weird i had to add 

```xml
        <dependency>
            <groupId>xerces</groupId>
            <artifactId>xercesImpl</artifactId>
            <version>2.12.1</version>
        </dependency>
        <dependency>
            <groupId>com.guicedee.services</groupId>
            <artifactId>xalan</artifactId>
            <version>1.2.0.3-jre17-rc1</version>
        </dependency>
```

to make it work.

**Comment by newk5** [comment]
Strange, I never had that error, nor do I have any of those dependencies. 
I am on JDK17 and Quarkus 2.6.2.Final, MF 2.3-next-M6, Omnifaces 3.11.2 with Omnifaces-quarkus 1.4.0
